apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moviebox-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.moviebox.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: moviebox-api
            port:
              number: 80
